include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 这些降为提示，不阻断构建
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false
